---
- name: Upgrade all packages to the latest version
  dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: Install utility packages (git, unzip)
  dnf:
    name:
      - git
      - unzip
    state: present

- name: Install fail2ban
  dnf:
    name: fail2ban
    state: present

- name: Ensure fail2ban is started and enabled
  service:
    name: fail2ban
    state: started
    enabled: yes
